### ISSUE TITLE
Distgen does not have setter for input -> affects sectormagnet example

### ISSUE THREAD

**Issue by petr-lanl** [ColwynGulliford/lume-gpt#7]
examples/elements/sectormagnet.ipynb cell 6 contains:
`gen.input['x_dist']={'type':'uniform', 'min_x': -0.1*unit_registry('m'), 'max_x': +0.1*unit_registry('m')}`

It assumes that distgen has a setter for property `input`. The version of distgen, which I have, has the setter commented out as a result weak focusing example does not work:
![image](https://github.com/ColwynGulliford/lume-gpt/assets/67295521/33f3b0e1-13c1-46fa-9852-eba76c1fdd10)
instead of
![image](https://github.com/ColwynGulliford/lume-gpt/assets/67295521/e1ded1d8-7877-490a-8b17-fd13e30824e2)

Same holds true for edge focusing part of the notebook

**Comment by ColwynGulliford** [comment]
Yes, that's correct - the new version of distgen doesn't have a setter for `Generator.input`, in fact that object is now a derived property (the details have to do with Distgen making use of the Pint package to handle physical units internally).  I will correct the notebook so that it use the up-to-date Distgen syntax:

gen['x_dist']={'type':'uniform', 'min_x': -0.1*unit_registry('m'), 'max_x': +0.1*unit_registry('m')}

**Comment by petr-lanl** [comment]
Thank you, I have now issue with cell 8 as you are using `fix=True` option. I believe that it calls for `sectormagent_fix` element that I do not have in my GPT install. What kind of element is that?

Removing `fix=True` seems to be working as expected. I however at cell 11 now and it gives me 
![image](https://github.com/ColwynGulliford/lume-gpt/assets/67295521/1ceb19d1-2fb2-4517-83b7-5e45f81ccb60)
...
![image](https://github.com/ColwynGulliford/lume-gpt/assets/67295521/6025b930-7862-43bb-b5e8-4df79a6a4403)

I do not understand the cause of the error yet.

**Comment by petr-lanl** [comment]
Finally, class `Sectormagnet` has method `track_ref` commented out. This causes cell 21 to fail since the fall back method of `super` does nothing.

**Comment by ColwynGulliford** [comment]
`sectormagnet_fix ` is an outdated version of the sectormagnet element in GPT - the original sectormagnet code had a bug in it at the time, so we were supplied with a version called "fixed".  However,  the fixed version is now the standard, so I removed that argument to Sectormagnet.

**Comment by ColwynGulliford** [comment]
I also used to have a separate element for Quadrupoles with fringes, however that is also included in GPT (probably for some time), so I'm updated the notebook on quadrupoles.

**Comment by ColwynGulliford** [comment]
I found a few more instances that needed updating, but think I caught them all (or most).  Please reopen this issue if you find any more.

**Comment by ColwynGulliford** [comment]
Ok, I've updated all the notebooks in examples/elements and checked they all run.
